services:
  gateway:
    image: ghcr.io/miralsnk/go-micro-blog/gateway:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M