name: Deploy to Dev

on:
    push:
        branches: ["dev"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Copy project to server via SCP
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_HOST_DEV }}
                  username: ${{ secrets.SERVER_USER_DEV }}
                  key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
                  source: "./"
                  target: "/home/${{ secrets.SERVER_USER_DEV }}/dev-blog/"
                  rm: true
                  strip_components: 0

            - name: Deploy with Docker Compose (dev)
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST_DEV }}
                  username: ${{ secrets.SERVER_USER_DEV }}
                  key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
                  script: |
                    mkdir -p /home/${{ secrets.SERVER_USER_DEV }}/dev-blog
                    cd /home/${{ secrets.SERVER_USER_DEV }}/dev-blog
                    docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
                    sleep 5
                    docker ps